name: bump-and-tag-build-version
on:
  push:
    target:
      - master
jobs:
  bump-and-tag-build-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: config git
        run: |
          git config user.name github-actions
          git config user.email github-actions@verishop.com
      - name: Bump build number
        run: npm version patch
      - name: Push package.json version update
        run: git push -f
      - name: Push tags
        run: git push --tags