name: upload-prod-build-output
on:
  release: 
    types:
      - created
jobs:
  build-and-upload-output-to-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install dependencies
        working-directory: ./sample-app
        run: npm install
      - name: build production output
        working-directory: ./sample-app
        run: npm run build